import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Header/Nav */}
        <header
          style={{
            position: "sticky",
            top: 0,
            zIndex: 50,
            background: "black",
            padding: "12px 16px",
            borderBottom: "1px solid rgba(255,255,255,0.1)",
          }}
        >
          <nav
            style={{
              display: "flex",
              alignItems: "center",
              gap: "16px",
              color: "white",
            }}
          >
            <Link href="/">Bit Pulse</Link>
            <div style={{ marginLeft: "auto", display: "flex", gap: "12px" }}>
              <Link href="/">Home</Link>
              <Link href="/lore">LORE</Link>
            </div>
          </nav>
        </header>

        {/* Page content */}
        {children}
      </body>
    </html>
  );
}
